crmdemo/urls.py
from django.contrib import admin
from django.urls import path


# from django.contrib import admin
from django.urls import path, include
from apps.web.stark import site  # 注意这里导入后web的site才生效
from apps.web.views import account

# print(site._registry)  # 显示stark组件注册信息
# print('路由开始加载。。。')

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login/', account.login_view, name='login'),
    path('logout/', account.logout_view, name='logout'),
    path('index/', account.index_view, name='index'),
    path('stark/', site.urls),
    path('rbac/', include('rbac.urls')),
]

rbac/service/urls.py
from django.urls import reverse
from django.http import QueryDict


def memory_url(request, name, *args, **kwargs):
    """生成带有原搜索条件的URL（替代了模板中的url)"""
    basic_url = reverse(name, args=args, kwargs=kwargs)
    # 如果当前URL无参数
    if not request.GET:
        return basic_url
    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()
    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """反向生成URL，并获取原来的搜索条件返回"""
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')
    if origin_params:
        url = "%s?%s" % (url, origin_params,)
    return url

rbac/urls.py
from django.urls import path
from rbac.views import role,user,menu


app_name = 'rbac'

urlpatterns = [
    path('role/list/', role.role_list, name='role_list'),
    path('role/add/', role.role_add, name='role_add'),
    path('role/edit/<int:pk>/', role.role_edit, name='role_edit'),
    path('role/del/<int:pk>/', role.role_del, name='role_del'),

    # path('user/list/', user.user_list, name='user_list'),
    # path('user/add/', user.user_add, name='user_add'),
    # path('user/edit/<int:pk>/', user.user_edit, name='user_edit'),
    # path('user/del/<int:pk>/', user.user_del, name='user_del'),
    # path('user/reset/password/<int:pk>/', user.user_reset_pwd, name='user_reset_pwd'),

    path('menu/list/', menu.menu_list, name='menu_list'),
    path('menu/add/', menu.menu_add, name='menu_add'),
    path('menu/edit/<int:pk>/', menu.menu_edit, name='menu_edit'),
    path('menu/del/<int:pk>/', menu.menu_del, name='menu_del'),
    path('second/menu/add/<int:menu_id>/', menu.second_menu_add, name='second_menu_add'),
    path('second/menu/edit/<int:pk>/', menu.second_menu_edit, name='second_menu_edit'),
    path('second/menu/del/<int:pk>/', menu.second_menu_del, name='second_menu_del'),
    path('permission/add/<int:second_menu_id>/', menu.permission_add, name='permission_add'),
    path('permission/edit/<int:pk>/', menu.permission_edit, name='permission_edit'),
    path('permission/del/<int:pk>/', menu.permission_del, name='permission_del'),

    path('multi/permissions/', menu.multi_permissions, name='multi_permissions'),
    path('multi/permissions/del/<int:pk>/', menu.multi_permissions_del, name='multi_permissions_del'),

    path('distribute/permissions/', menu.distribute_permissions, name='distribute_permissions'),

]

rbac/forms/base.py
from django import forms


class BootStrapModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BootStrapModelForm,self).__init__(*args,**kwargs)
        # 统一给ModelForm生成的字段添加样式
        for name,field in self.fields.items():
            field.widget.attrs['class']='form-control'

rbac/forms/role.py
from rbac import models
from django import forms


class RoleModelForm(forms.ModelForm):
    class Meta:
        model = models.Role
        fields = ['title',]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }

rbac/service/routes.py
# -*- coding:utf-8 -*-

import re
from collections import OrderedDict
from django.conf import settings
from django.utils.module_loading import import_string  # 根据字符串的形式，帮我们去导入模块
from django.urls import URLPattern, URLResolver  # 路由分发：URLResolver。不是路由分发：URLPattern


def check_url_exclude(url):
    """
    排除一些特定的URL
    :param url:
    :return:
    """
    for regex in settings.AUTO_DISCOVER_EXCLUDE:
        if re.match(regex, url):
            return True


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    递归的去获取URL
    :param pre_namespace: namespace前缀，以后用户拼接name
    :param pre_url: url前缀，以后用于拼接url
    :param urlpatterns: 路由关系列表
    :param url_ordered_dict: 用于保存递归中获取的所有路由
    :return:
    """
    for item in urlpatterns:
        if isinstance(item, URLPattern):  # 非路由分发，讲路由添加到url_ordered_dict
            if not item.name:   # url中反向命名的name
                continue

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name)
                # print(name)
            else:
                name = item.name
            # url = pre_url + item._regex
            url = pre_url + item.pattern.regex.pattern   # /^rbac/^user/edit/(?P<pk>\d_+)/$
            url = url.replace('^', '').replace('$', '')  # /rbac/user/edit/(?P<pk>\d+)/

            if check_url_exclude(url):
                continue

            url_ordered_dict[name] = {'name': name, 'url': url}

        elif isinstance(item, URLResolver):  # 路由分发，递归操作

            if pre_namespace:
                if item.namespace:   # 多级分发 rbac:x1:n1
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = item.namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            recursion_urls(namespace, pre_url + item.pattern.regex.pattern, item.url_patterns, url_ordered_dict)


def get_all_url_dict():
    """
    获取项目中所有的URL（必须有name别名）
    :return:
    """
    url_ordered_dict = OrderedDict()
    """
    {
        'rbac:menu_list':{name:'rbac:menu_list',url:'xxxxx/yyyy/menu/list'}
    }
    """

    md = import_string(settings.ROOT_URLCONF)  # from luff.. import urls
    # for item in md.urlpatterns:
    #     print(item)
    recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)  # 递归去获取所有的路由

    return url_ordered_dict

rbac/views/menu.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from rbac import models
from rbac.forms.menu import MenuModelForm,SecondMenuModelForm,PermissionModelForm,MultiAddPermissionForm,MultiEditPermissionForm
from rbac.service.urls import memory_reverse
from django.db.models import Count
from collections import OrderedDict
from rbac.service.routes import get_all_url_dict
from django.forms import formset_factory
from django.conf import settings
from django.utils.module_loading import import_string



def menu_list(request):
    """菜单和权限列表"""

    menus = models.Menu.objects.annotate(menu_count=Count("menus__id"))
    menu_id = request.GET.get('mid')   # 用户选择的一级菜单
    second_menu_id = request.GET.get('sid')   # 用户选择的二级菜单

    menu_exists = models.Menu.objects.filter(id=menu_id).exists()
    if not menu_exists:
        menu_id = None

    if menu_id:
        second_menus = models.Permission.objects.filter(menu_id=menu_id)
    else:
        second_menus = []

    second_menu_exists = models.Permission.objects.filter(id=second_menu_id).exists()
    if not second_menu_exists:
        second_menu_id = None

    if second_menu_id:
        permissions = models.Permission.objects.filter(parent_id=second_menu_id)
    else:
        permissions = []

    context = {
        'menus': menus,
        'menu_id': menu_id,
        'second_menus': second_menus,
        'second_menu_id': second_menu_id,
        'permissions': permissions,
    }

    return render(request, 'rbac/menu_list.html',context=context)


def menu_add(request):
    """ 添加一级菜单 """
    if request.method == 'GET':
        form = MenuModelForm()
        return render(request, 'rbac/change.html',{'form':form})

    form = MenuModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})



def menu_edit(request,pk):
    """ 修改一级菜单 """
    obj = models.Menu.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('菜单不存在')

    if request.method == 'GET':
        form = MenuModelForm(instance=obj)
        return render(request, 'rbac/change.html',{'form':form})

    form = MenuModelForm(instance=obj,data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})


def menu_del(request,pk):
    """删除一级菜单"""
    origin_url = memory_reverse(request,'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html',{'cancel': origin_url})

    if request.method == 'POST':
        models.Menu.objects.filter(id=pk).delete()
        return redirect(origin_url)


def second_menu_add(request,menu_id):
    """ 添加二级菜单 """
    menu_object = models.Menu.objects.filter(id=menu_id).first()

    if request.method == 'GET':
        form = SecondMenuModelForm(initial={
            'menu': menu_object
        })
        return render(request, 'rbac/change.html',{'form':form})

    form = SecondMenuModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})


def second_menu_edit(request,pk):
    """ 编辑二级菜单 """
    permission_object = models.Permission.objects.filter(id=pk).first()

    if request.method == 'GET':
        form = SecondMenuModelForm(instance=permission_object)
        return render(request, 'rbac/change.html',{'form':form})

    form = SecondMenuModelForm(data=request.POST,instance=permission_object)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})



def second_menu_del(request,pk):
    """删除二级菜单"""
    origin_url = memory_reverse(request,'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html',{'cancel': origin_url})

    if request.method == 'POST':
        models.Permission.objects.filter(id=pk).delete()
        return redirect(origin_url)



def permission_add(request, second_menu_id):
    """增加权限"""

    if request.method == 'GET':
        form = PermissionModelForm()
        return render(request, 'rbac/change.html',{'form':form})

    form = PermissionModelForm(data=request.POST)
    if form.is_valid():
        second_menu_object = models.Permission.objects.filter(id=second_menu_id).first()
        if not second_menu_object:
            return HttpResponse('二级菜单不存在，请重新选择！')

        # form.instance中包含用户提交的所有值
        # 原来 instance = models.Permission(title='xxx',name='xxx',url='xxx')
        # 增加 instance.parent = second_menu_object
        # 则有 instance = models.Permission(title='xxx',name='xxx',url='xxx',parent=second_menu_object)
        form.instance.parent = second_menu_object
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})


def permission_edit(request,pk):
    """ 编辑权限 """
    permission_object = models.Permission.objects.filter(id=pk).first()

    if request.method == 'GET':
        form = PermissionModelForm(instance=permission_object)
        return render(request, 'rbac/change.html',{'form':form})

    form = PermissionModelForm(data=request.POST,instance=permission_object)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request,'rbac:menu_list'))

    return render(request, 'rbac/change.html',{'form':form})



def permission_del(request,pk):
    """删除权限"""
    origin_url = memory_reverse(request,'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html',{'cancel': origin_url})

    if request.method == 'POST':
        models.Permission.objects.filter(id=pk).delete()
        return redirect(origin_url)




def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')
    generate_formset_class = formset_factory(MultiAddPermissionForm, extra=0)
    update_formset_class = formset_factory(MultiEditPermissionForm, extra=0)

    generate_formset = None
    update_formset = None
    if request.method == 'POST' and post_type == 'generate':
        # pass # 批量添加
        formset = generate_formset_class(data=request.POST)
        if formset.is_valid():
            object_list = []
            post_row_list = formset.cleaned_data
            has_error = False
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                try:
                    new_object = models.Permission(**row_dict)
                    new_object.validate_unique()
                    object_list.append(new_object)
                except Exception as e:
                    formset.errors[i].update(e)
                    generate_formset = formset
                    has_error = True
            if not has_error:
                models.Permission.objects.bulk_create(object_list, batch_size=100)
        else:
            generate_formset = formset

    if request.method == 'POST' and post_type == 'update':
        # pass  # 批量更新
        formset = update_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                permission_id = row_dict.pop('id')
                try:
                    row_object = models.Permission.objects.filter(id=permission_id).first()
                    for k, v in row_dict.items():
                        setattr(row_object, k, v)
                    row_object.validate_unique()
                    row_object.save()
                except Exception as e:
                    formset.errors[i].update(e)
                    update_formset = formset
        else:
            update_formset = formset

    # 1. 获取项目中所有的URL
    all_url_dict = get_all_url_dict()
    # for k,v in all_url_dict.items():
    #     print(k,v)
    """
    {
        'rbac:role_list':{'name': 'rbac:role_list', 'url': '/rbac/role/list/'},
        'rbac:role_edit':{'name': 'rbac:role_edit', 'url': '/rbac/role/edit/(?P<pk>[0-9]+)/'},
        ....
    }
    """
    router_name_set = set(all_url_dict.keys())

    # 2. 获取数据库中所有的URL
    permissions = models.Permission.objects.all().values('id', 'title', 'name', 'url', 'menu_id', 'parent_id')
    permission_dict = OrderedDict()
    permission_name_set = set()
    for row in permissions:
        permission_dict[row['name']] = row
        permission_name_set.add(row['name'])
    """
    {
        'rbac:role_list': {'id':1,'title':'角色列表',name:'rbac:role_list',url.....},
        'rbac:role_add': {'id':1,'title':'添加角色',name:'rbac:role_add',url.....},
        ...
    }
    """

    for name, value in permission_dict.items():
        router_row_dict = all_url_dict.get(name)  # {'name': 'rbac:role_list', 'url': '/rbac/role/list/'},
        if not router_row_dict:
            continue
        if value['url'] != router_row_dict['url']:
            value['url'] = '路由：%s 和数据库不一致' % (router_row_dict['url'])

    # 3. 应该添加、删除、修改的权限有哪些？
    # 3.1 计算出应该增加的name
    if not generate_formset:
        generate_name_list = router_name_set - permission_name_set
        generate_formset = generate_formset_class(
            initial=[row_dict for name, row_dict in all_url_dict.items() if name in generate_name_list])

    # 3.2 计算出应该删除的name
    delete_name_list = permission_name_set - router_name_set
    delete_row_list = [row_dict for name, row_dict in permission_dict.items() if name in delete_name_list]

    # 3.3 计算出应该更新的name
    if not update_formset:
        update_name_list = permission_name_set & router_name_set
        update_formset = update_formset_class(

rbac/views/role.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from rbac import models
from rbac.forms.role import RoleModelForm
from django.db.models import Count



def role_list(request):
    """角色列表"""
    role_queryset = models.Role.objects.annotate(permission_count=Count("permissions__id"))

    # print(role_queryset.explain())
    return render(request, 'rbac/role_list.html', {'roles': role_queryset})



def role_add(request):
    """添加角色"""
    if request.method == 'GET':
        form = RoleModelForm()
        return render(request, 'rbac/change.html',{'form':form})

    form = RoleModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))

    return render(request, 'rbac/change.html',{'form':form})



def role_edit(request,pk):
    """编辑角色"""
    obj = models.Role.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')

    if request.method == 'GET':
        form = RoleModelForm(instance=obj)
        return render(request, 'rbac/change.html',{'form':form})

    form = RoleModelForm(instance=obj,data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))

    return render(request, 'rbac/change.html',{'form':form})



def role_del(request,pk):
    """删除角色"""
    origin_url = reverse('rbac:role_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html',{'cancel': origin_url})

    if request.method == 'POST':
        models.Role.objects.filter(id=pk).delete()
        return redirect(origin_url)

rbac/templates/rbac/breadcrumb.html
<div style="margin-bottom: 15px;">
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd; background: white; font-weight: bold;">
        <i class="fa fa-dashboard" aria-hidden="true" style="margin-right: 5px;"></i>
        {% for item in breadcrumb_list %}
            {% if forloop.last %}
                <li class="active">{{ item.title }}</li>
            {% else %}
                <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

rbac/templates/rbac/change.html
{% extends 'layout.html' %}

{% block head %}
    <style>
        .icon-area {
            list-style-type: none;
            padding: 0;
        }

        .icon-area li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <form class="form-horizontal" method="post" novalidate style="margin-top: 15px;">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span style="color: red;">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                            <input class="btn btn-primary" type="submit" value="保 存">
                            <a class="btn btn-default" href="JavaScript:history.back(-1)">取 消</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert fade in" style="color: #a94442;background-color: #f2dede; border-color: #ebccd1;" role="alert">
                <form method="post">
                    {% csrf_token %}
                    <h4>删除操作</h4>
                    <p style="font-size: 14px;padding-top: 20px;padding-bottom: 20px;">
                        <i class="fa fa-warning" aria-hidden="true"></i>
                        删除后将不可恢复，请确定是否删除？
                    </p>
                    <div style="margin-top: 20px;">
                        <a href="{{ cancel }}" class="btn btn-sm" style="background-color: #f4f4f4;color: #444;border-color: #ddd;text-decoration: none;">取 消</a>
                        <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
        <form method="post" action="?type=generate">
            {% csrf_token %}
            {{ generate_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-list" aria-hidden="true"></i> 待新建权限列表
                    <button href="#" class="btn btn-primary btn-xs pull-right"
                            style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        保存
                    </button>
                </div>
                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>菜单</th>
                        <th>父权限</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in generate_formset %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% for field in  form %}
                                <td>{{ field }}<span style="color: red;">{{ field.errors.0 }}</span></td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-list" aria-hidden="true"></i> 待删除权限列表
            </div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>删除</th>
                </tr>
                </thead>
                <tbody>
                {% for row in delete_row_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ row.title }}</td>
                        <td>{{ row.url }}</td>
                        <td>{{ row.name }}</td>
                        <td>
                            <a style="color: #d9534f;" href="{% url 'rbac:multi_permissions_del' pk=row.id %}">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-list" aria-hidden="true"></i> 待更新权限列表
                    <button href="#" class="btn btn-primary btn-xs pull-right"
                            style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        保存
                    </button>
                </div>
                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>菜单</th>
                        <th>父权限</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% for field in  form %}
                                {% if forloop.first %}
                                    {{ field }}
                                {% else %}
                                    <td>{{ field }}<span style="color: red;">{{ field.errors.0 }}</span></td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
        </div>
    </div>

{% endblock %}

rbac/templates/rbac/multimenu.html
<ul class="multi-menu sidebar-menu" data-widget="tree">
    {% for item in menu_dict.values %}
        <li class="treeview">
            <a href="#">
                <i class="fa {{ item.icon }}"></i> <span> {{ item.title }}</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                {% for per in item.children %}
                    <li>
                        <a href="{{ per.url }}" class="{{ per.class }}">
                            <i class="fa fa-caret-right"></i>
                            <span>{{ per.title }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>


<script>
    $(function () {
        $('.sidebar-menu li:not(.treeview) > a').on('click', function () {
            var $parent = $(this).parent().addClass('active');
            $parent.siblings('.treeview.active').find('> a').trigger('click');
            $parent.siblings().removeClass('active').find('li').removeClass('active');
        });
        $(function () {
            $('.sidebar-menu a').each(function () {
                if ($(this).hasClass('active')) {
                    //console.log(this.href === window.location.href);
                    $(this).parent().addClass('active')
                        .closest('.treeview-menu').addClass('.menu-open')
                        .closest('.treeview').addClass('active');
                }
            });
        });
    });
</script>

rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i> 角色列表
                    <div class="btn-group pull-right">
                        <a href="{% url 'rbac:role_add' %}" class="btn btn-success btn-xs">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            新建角色
                        </a>
                    </div>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>角色名称</th>
                        <th>权限数量</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in roles %}
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.title }}</td>
                            <td>{{ row.permission_count }}</td>
                            <td style="width: 20%;">
                                <a href="{% url 'rbac:role_edit' pk=row.id %}" style="display: inline-block;">
                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                </a>

                                <a href="{% url 'rbac:role_del' pk=row.id %}"
                                   style="color: #d9534f;display: inline-block;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-users" aria-hidden="true"></i> 用户列表
                    <div class="btn-group pull-right">
                        <a href="{% url 'rbac:user_add' %}" class="btn btn-success btn-xs">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            新建用户
                        </a>
                    </div>
                </div>
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>用户名</th>
                        <th>邮箱</th>
                        <th>重置密码</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in users %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ row.name }}</td>
                            <td>{{ row.email }}</td>
                            <td><a href="{% url 'rbac:user_reset_pwd' pk=row.id %}">重置密码</a></td>
                            <td style="width: 20%;">
                                <a href="{% url 'rbac:user_edit' pk=row.id %}" style="display: inline-block;">
                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                </a>

                                <a href="{% url 'rbac:user_del' pk=row.id %}" style="color: #d9534f;display: inline-block;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}